name: PR Verification
on: 
  pull_request:
    branches:
      - master
jobs:
  Verification:
    runs-on: ubuntu-latest
    environment: test
    steps:
      -
        name: "Test"
        run: echo "RELEASE_VERSION
