name: PR Verification
on: 
  pull_request:
    branches:
      - main
jobs:
  Verification:
    if: ! github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    environment: test
    steps:
      -
        name: "Test"
        run: |
          echo  ${{ github.event.pull_request.head.repo.fork }}
          echo "VERIFICATIOn DONE"
